### ISSUE TITLE
Deadline scheduler

### ISSUE THREAD

**Issue by kurtextrem** [spakkkk/SKIZO-chiron#10]
Hi spak, thank you for your great kernel. I just noticed that the deadline scheduler is not available in your kernel (only noop and cfq).
According to the Ubuntu Kernel Team, deadline is the best kernel available for SSDs: https://wiki.ubuntu.com/Kernel/Reference/IOSchedulers. Can you please add it back?

**Comment by spakkkk** [comment]
Our CFQ it's updated, and is the best scheduler for mobile devices.
Thanks
