### ISSUE TITLE
Boefflas Kernel Wakelock Blocker

### ISSUE THREAD

**Issue by kurtextrem** [spakkkk/SKIZO-chiron#11]
I think Boefflas Kernel Wakelock Blocker is a great tool to save battery. The placeholder kernel has it as well. Is there anything holding you back adding this?

**Comment by spakkkk** [comment]
Boeffla it's useless, the doze system on P and Q works flawlessly!
thanks

**Comment by kurtextrem** [comment]
Afaik doze only blocks wakelocks etc from the user space, not the kernel. Boefflas wakelock blocker is for kernel wakelocks.
