### ISSUE TITLE
Why did you remove "maple" io sched? 

### ISSUE THREAD

**Issue by kurtextrem** [spakkkk/SKIZO-chiron#5]
Just curious.

**Comment by spakkkk** [comment]
cfq is the best iosched by far :)

**Comment by kurtextrem** [comment]
Hm, I've seen different: https://androidmodguide.blogspot.com/p/io-schedulers.html
Zen and fiops come out on top, and maple is based on Zen. So I assumed it's one of the best to choose. Cfq seemed to be on the last place almost everywhere.

Might be different for the Mix 2 though? Not sure.

**Comment by spakkkk** [comment]
that article its a little bit outdated.. with updates cfq its better overall

https://forum.xda-developers.com/showpost.php?p=59289783&postcount=3

**Comment by spakkkk** [comment]
https://youtu.be/dSknEcbxg74

**Comment by kurtextrem** [comment]
I see, thanks.
