### ISSUE TITLE
instant battery current data update problem, and could you release a no-undervolt version?

### ISSUE THREAD

**Issue by ghost** [spakkkk/SKIZO-chiron#7]
I'm a new mix 2 user, using Lineage15.1 20181029 with firmware 8.4.19, Skizo 024. 

For instant battery current data update problem:
It's only updated every 5 seconds (via CpuFloat/Accubattery etc), and with Lineage stock kernel it's updated every second.
Or is this just a power-saving setting?

For no-undervolt version:
I have read the closed issue#6(Freezes and reboots), so I have disabled overclock and /vendor/etc/perf.
But I still notice freeze and auto-reboot. Is this due to undervolt too much?
Maybe my 835 is not as good as yours.

Thanks!

**Comment by spakkkk** [comment]
Hi,

Try to update firmware to 8.9.20 and give me feedback then, the update its "mandatory" since 008.

Overclock its disabled by default, and its the first feedback with that issue, maybe its firmware related, btw join this channel:
https://t.me/mix2development

And send me /sys/fs/pstore/console-ramoops after reboot in pm.

I will close this issue.

Thanks for your feedback!

**Comment by ghost** [comment]
Hi spak.
I've updated to firmware 8.9.20, and re-flashed skizo 024b.
Here is a screenshot of last a few log before an auto reboot. (When I plug change cable in and press power button to close the screen, it reboots. And it won't 100% reboot in this situation XD)
[screenshot](https://imgchr.com/i/ib8NIH)

Battery current update frequency problem still exists. When cable isn't' plug in, battery current updates every 5 seconds. And when it's charging, update once per second. Any way it's just a small flaw.

Sorry but I can't message you on Telegram. I live in mainland China, and it's forbidden to start a chat with people outside the contact list by Telegram.  _(:з」∠)_

Full log txt:
[console-ramoops-0.txt](https://github.com/spakkkk/chiron_skizo/files/2565273/console-ramoops-0.txt)

**Comment by spakkkk** [comment]
try new version and give feedback brah!
thanks!

**Comment by ghost** [comment]
Thanks for your new 025b version, new kernel works very stable for over 18 hours ! 
LOL
