### ISSUE TITLE
Media (audio) and calls stop working if I flash a kernel newer than skizo-pcaf-sagit-20190121v2.zip

### ISSUE THREAD

**Issue by imdos** [spakkkk/SKIZO-chiron#8]
Hi spak,

I have a problem with newer releases of your kernel or somewhere in my "running" config.
Usually I flash my MI6 once a week or so to a new release of LOS15.1; opengapps, skizo and latest magisk.

The procedure I follow is reboot to TWRP; backup all partitions; flash cache and dalvik and install the zip's. After that I auto reboot and sometimes I reboot my phone again; but not always. 

I noticed that with newer zip's (then: skizo-pcaf-sagit-20190121v2.zip) from sagit I'm unable to control the media volume level nor does any notification work. It even occurred that I couldn't hear someone who tried to call me on my mobile through whatsapp or plain GSM. The audio for movies and AFAIK inside calls are not broken.

Please help me how to resolve this; or suggest what to do to debug this.

**Comment by spakkkk** [comment]
I don't support sagit and oreo.
BTW that's probably not kernel related. 

Closed. 
Thanks!
